// Generated by tools/generate_mini_logo_overrides.py. Do not edit.
#pragma once

struct MiniGeneratedLogoOverride {
  const char* key;
  const char* url;
};

static const MiniGeneratedLogoOverride MINI_GENERATED_LOGO_OVERRIDES[] = {
  {"MARCH_MADNESS:IOWA", "https://a.espncdn.com/guid/b7840e2f-6236-e764-2cae-20286a0829e7/logos/primary_logo_on_black_color.png"},
  {"MLB:COL", "https://raw.githubusercontent.com/MattLD13/PoopTracker/refs/heads/main/Colorado_Rockies_logo.svg.png"},
  {"MLB:HOU", "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png"},
  {"MLB:MIA", "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png"},
  {"MLB:NYY", "https://raw.githubusercontent.com/MattLD13/PoopTracker/refs/heads/main/New_York_Yankees_logo.svg.png"},
  {"MLB:SD", "https://a.espncdn.com/guid/4dec648c-3eb9-055c-aebc-2711f30975a0/logos/primary_logo_on_primary_color.png"},
  {"MLB:WAS", "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png"},
  {"MLB:WSH", "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png"},
  {"NBA:HOU", "https://a.espncdn.com/i/teamlogos/nba/500/hou.png"},
  {"NBA:IND", "https://a.espncdn.com/i/teamlogos/nba/500/ind.png"},
  {"NBA:MIA", "https://a.espncdn.com/i/teamlogos/nba/500/mia.png"},
  {"NBA:WAS", "https://a.espncdn.com/i/teamlogos/nba/500/was.png"},
  {"NBA:WSH", "https://a.espncdn.com/i/teamlogos/nba/500/was.png"},
  {"NCF_FBS:CAL", "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png"},
  {"NCF_FBS:HOU", "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png"},
  {"NCF_FBS:IND", "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png"},
  {"NCF_FBS:MIA", "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png"},
  {"NCF_FBS:MIAMI", "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png"},
  {"NCF_FBS:ORST", "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png"},
  {"NCF_FBS:OSU", "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png"},
  {"NCF_FBS:WASH", "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png"},
  {"NCF_FCS:LEH", "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png"},
  {"NCF_FCS:LIN", "https://a.espncdn.com/i/teamlogos/ncaa/500/2815.png"},
  {"NFL:HOU", "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"},
  {"NFL:IND", "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png"},
  {"NFL:MIA", "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png"},
  {"NFL:WAS", "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"},
  {"NFL:WSH", "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"},
  {"NHL:LAK", "https://a.espncdn.com/i/teamlogos/nhl/500/la.png"},
  {"NHL:NJD", "https://a.espncdn.com/i/teamlogos/nhl/500/nj.png"},
  {"NHL:SJS", "https://a.espncdn.com/i/teamlogos/nhl/500/sj.png"},
  {"NHL:TBL", "https://a.espncdn.com/i/teamlogos/nhl/500/tb.png"},
  {"NHL:UTA", "https://a.espncdn.com/i/teamlogos/nhl/500/utah.png"},
  {"NHL:VEG", "https://a.espncdn.com/i/teamlogos/nhl/500/vgs.png"},
  {"NHL:VGK", "https://a.espncdn.com/i/teamlogos/nhl/500/vgs.png"},
  {"NHL:WAS", "https://a.espncdn.com/guid/cbe677ee-361e-91b4-5cae-6c4c30044743/logos/secondary_logo_on_black_color.png"},
  {"NHL:WSH", "https://a.espncdn.com/guid/cbe677ee-361e-91b4-5cae-6c4c30044743/logos/secondary_logo_on_black_color.png"},
};

static constexpr size_t MINI_GENERATED_LOGO_OVERRIDE_COUNT = sizeof(MINI_GENERATED_LOGO_OVERRIDES) / sizeof(MINI_GENERATED_LOGO_OVERRIDES[0]);
