"""Generate mini firmware logos from the centralized override table."""

from __future__ import annotations

import sys
from collections.abc import Callable
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sports_ticker.providers.logo_overrides import LOGO_OVERRIDES
from ticker_core.assets.processors import prepare_contained


OUTPUT = ROOT / "esp32_hub75" / "src" / "mini" / "assets" / "logo_overrides_generated.h"
LOGO_SIZE = (18, 18)


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def fetch(url: str) -> bytes:
    response = requests.get(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 MiniTickerAssetBuilder/1.0",
            "Accept": "image/png,image/jpeg,image/*,*/*;q=0.8",
        },
        timeout=20,
    )
    response.raise_for_status()
    return response.content


def encode(raw: bytes) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """Use the large ticker processor, then encode one RGB565 image and mask."""

    image = prepare_contained(raw, LOGO_SIZE)
    pixels: list[int] = []
    mask = bytearray((LOGO_SIZE[0] * LOGO_SIZE[1] + 7) // 8)
    for index, (red, green, blue, alpha) in enumerate(image.getdata()):
        if alpha:
            mask[index // 8] |= 1 << (index % 8)
            red = red * alpha // 255
            green = green * alpha // 255
            blue = blue * alpha // 255
            pixels.append(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3))
        else:
            pixels.append(0)
    return tuple(pixels), tuple(mask)


def format_values(values: tuple[int, ...], *, width: int, columns: int) -> str:
    rendered = [f"0x{value:0{width}X}" for value in values]
    return "\n".join(
        "  " + ", ".join(rendered[index : index + columns]) + ","
        for index in range(0, len(rendered), columns)
    )


def render(fetcher: Callable[[str], bytes] = fetch) -> str:
    unique_urls = tuple(dict.fromkeys(LOGO_OVERRIDES.values()))
    encoded = {url: encode(fetcher(url)) for url in unique_urls}
    url_indexes = {url: index for index, url in enumerate(unique_urls)}

    asset_blocks: list[str] = []
    for index, url in enumerate(unique_urls):
        pixels, mask = encoded[url]
        asset_blocks.append(
            f"// {url}\n"
            f"static const uint16_t MINI_GENERATED_LOGO_PIXELS_{index}[] PROGMEM = {{\n"
            f"{format_values(pixels, width=4, columns=12)}\n"
            "};\n"
            f"static const uint8_t MINI_GENERATED_LOGO_MASK_{index}[] PROGMEM = {{\n"
            f"{format_values(mask, width=2, columns=16)}\n"
            "};"
        )

    rows = "\n".join(
        "  {"
        f'"{escape(key)}", "{escape(url)}", '
        f"MINI_GENERATED_LOGO_PIXELS_{url_indexes[url]}, MINI_GENERATED_LOGO_MASK_{url_indexes[url]}"
        "},"
        for key, url in sorted(LOGO_OVERRIDES.items())
    )
    assets = "\n\n".join(asset_blocks)
    return (
        "// Generated by tools/generate_mini_logo_overrides.py. Do not edit.\n"
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        "struct MiniGeneratedLogoOverride {\n"
        "  const char* key;\n"
        "  const char* sourceUrl;\n"
        "  const uint16_t* pixels;\n"
        "  const uint8_t* mask;\n"
        "};\n\n"
        f"{assets}\n\n"
        "static const MiniGeneratedLogoOverride MINI_GENERATED_LOGO_OVERRIDES[] = {\n"
        f"{rows}\n"
        "};\n\n"
        "static constexpr size_t MINI_GENERATED_LOGO_OVERRIDE_COUNT = "
        "sizeof(MINI_GENERATED_LOGO_OVERRIDES) / sizeof(MINI_GENERATED_LOGO_OVERRIDES[0]);\n"
    )


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
