"""Generate the mini firmware fallback logo override table."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sports_ticker.providers.logo_overrides import LOGO_OVERRIDES


OUTPUT = ROOT / "esp32_hub75" / "src" / "mini" / "assets" / "logo_overrides_generated.h"


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render() -> str:
    rows = "\n".join(
        f'  {{"{escape(key)}", "{escape(value)}"}},'
        for key, value in sorted(LOGO_OVERRIDES.items())
    )
    return (
        "// Generated by tools/generate_mini_logo_overrides.py. Do not edit.\n"
        "#pragma once\n\n"
        "struct MiniGeneratedLogoOverride {\n"
        "  const char* key;\n"
        "  const char* url;\n"
        "};\n\n"
        "static const MiniGeneratedLogoOverride MINI_GENERATED_LOGO_OVERRIDES[] = {\n"
        f"{rows}\n"
        "};\n\n"
        "static constexpr size_t MINI_GENERATED_LOGO_OVERRIDE_COUNT = "
        "sizeof(MINI_GENERATED_LOGO_OVERRIDES) / sizeof(MINI_GENERATED_LOGO_OVERRIDES[0]);\n"
    )


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
